ROLE_ADMIN_SYSTEM = "administrator_system"
ROLE_ADMIN_CAMPAIGN = "administrator_campaign"
ROLE_INTERVENANT = "intervenant_terrain"
ROLE_ANALYSTE = "analyste"
ROLE_DEV_SUPERUSER = "developer_superuser"

DEFAULT_ROLES = [
    ROLE_ADMIN_SYSTEM,
    ROLE_ADMIN_CAMPAIGN,
    ROLE_INTERVENANT,
    ROLE_ANALYSTE,
    ROLE_DEV_SUPERUSER,
]

RESOURCE_USERS = "users"
RESOURCE_ZONES = "zones"
RESOURCE_CAMPAIGNS = "campaigns"
RESOURCE_ASSIGNMENTS = "assignments"
RESOURCE_DATA = "data"
RESOURCE_ANALYTICS = "analytics"
RESOURCE_ME = "me"
RESOURCE_SYNC = "sync"
RESOURCE_CONFLICTS = "conflicts"
RESOURCE_AUDIT_LOGS = "audit_logs"

ACTION_CREATE = "create"
ACTION_READ = "read"
ACTION_UPDATE = "update"
ACTION_DELETE = "delete"

ROLE_PERMISSIONS: dict[str, set[tuple[str, str]]] = {
    ROLE_ADMIN_SYSTEM: {
        (RESOURCE_USERS, ACTION_CREATE),
        (RESOURCE_USERS, ACTION_READ),
        (RESOURCE_USERS, ACTION_UPDATE),
        (RESOURCE_USERS, ACTION_DELETE),
        (RESOURCE_ANALYTICS, ACTION_READ),
        (RESOURCE_DATA, ACTION_READ),
        (RESOURCE_CONFLICTS, ACTION_READ),
        (RESOURCE_CONFLICTS, ACTION_UPDATE),
        (RESOURCE_AUDIT_LOGS, ACTION_READ),
    },
    ROLE_ADMIN_CAMPAIGN: {
        (RESOURCE_USERS, ACTION_READ),
        (RESOURCE_ZONES, ACTION_CREATE),
        (RESOURCE_ZONES, ACTION_READ),
        (RESOURCE_ZONES, ACTION_UPDATE),
        (RESOURCE_CAMPAIGNS, ACTION_CREATE),
        (RESOURCE_CAMPAIGNS, ACTION_READ),
        (RESOURCE_CAMPAIGNS, ACTION_UPDATE),
        (RESOURCE_ASSIGNMENTS, ACTION_CREATE),
        (RESOURCE_ASSIGNMENTS, ACTION_READ),
        (RESOURCE_DATA, ACTION_READ),
    },
    ROLE_INTERVENANT: {
        (RESOURCE_ME, ACTION_READ),
        (RESOURCE_DATA, ACTION_CREATE),
        (RESOURCE_DATA, ACTION_READ),
        (RESOURCE_SYNC, ACTION_CREATE),
    },
    ROLE_ANALYSTE: {
        (RESOURCE_ANALYTICS, ACTION_READ),
        (RESOURCE_DATA, ACTION_READ),
        (RESOURCE_CAMPAIGNS, ACTION_READ),
    },
}
