apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: e-sante-ism-spum
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
